import { Livro } from "@/classes/modelo/Livro";
import { Menu } from "@/componentes/Menu";
import { NextPage } from "next"
import Head from "next/head";
import Router from "next/router";
import { useState } from "react";
import { controleEditora } from "./api/editoras";
import styles from '../styles/Home.module.css'
import { ControleLivro } from "@/classes/controle/ControleLivro";

const opcoes = controleEditora.getEditoras().map(x => { return { value: x.codEditora, name: x.nome } });

const LivroDados: NextPage = () => {
    const controleLivros = new ControleLivro();

    const [titulo, setTitulo] = useState("");
    const [resumo, setResumo] = useState("");
    const [autores, setAutores] = useState("");
    const [codEditora, setCodEditora] = useState(opcoes[0]);

    const tratarCombo = (evento: React.ChangeEvent<HTMLSelectElement>): any => {
        let codEditora = parseInt(evento.target.value)
        setCodEditora(opcoes.filter(x => x.value === codEditora)[0]);
    }

    const incluir = (evento: React.FormEvent<HTMLFormElement>): any => {
        debugger;
        evento.preventDefault();
        let livro = new Livro("", codEditora.value, titulo, resumo, autores.split('\n'));
        controleLivros.incluir(livro).then(() => {
            Router.push({ pathname: '/LivroLista' })
        });
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Loja Next</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Menu></Menu>
            <main>
                <form onSubmit={incluir}>
                    <div className="row gx-0 pb-2">
                        <h1>Dados do Livro</h1>
                    </div>

                    <div className="row gx-0 pb-2">
                        <label>Titulo</label>
                        <input className="form-control" value={titulo} onChange={e => setTitulo(e.target.value)}></input>
                    </div>

                    <div className="row gx-0 pb-2">
                        <label>Resumo</label>
                        <textarea className="form-control" value={resumo} onChange={e => setResumo(e.target.value)}></textarea>
                    </div>

                    <div className="row gx-0 pb-2">
                        <label>Editora</label>
                        <select className="form-control" onChange={tratarCombo}>
                            {opcoes.map(x => { return <option key={x.value} value={x.value}>{x.name}</option> })}
                        </select>
                    </div>

                    <div className="row gx-0">
                        <label>Autores</label>
                        <textarea className="form-control" value={autores} onChange={e => setAutores(e.target.value)}></textarea>
                    </div>
                    <br></br>

                    <div className="row gx-0">
                        <div className="col">
                            <input className={"btn btn-primary"} type={"submit"} value={"Salvar Dados"}></input>
                        </div>
                    </div>
                </form>
            </main>
        </div>
    )
}

export default LivroDados;